---
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: set Asia/Tokyo to date.timezone on php.ini
  lineinfile:
    dest: /etc/php.ini
    backrefs: yes
    regexp: '^;date.timezone ='
    line: 'date.timezone = Asia/Tokyo'
